package com.goku.coreui.sys.model;

import java.util.Date;

public class SysUserInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.head_portrait
     *
     * @mbg.generated
     */
    private String headPortrait;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.post_code
     *
     * @mbg.generated
     */
    private String postCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.height
     *
     * @mbg.generated
     */
    private String height;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.weight
     *
     * @mbg.generated
     */
    private String weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.birthday
     *
     * @mbg.generated
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.blood
     *
     * @mbg.generated
     */
    private String blood;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.culture
     *
     * @mbg.generated
     */
    private String culture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.finish_school_date
     *
     * @mbg.generated
     */
    private Date finishSchoolDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.folk
     *
     * @mbg.generated
     */
    private String folk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.government
     *
     * @mbg.generated
     */
    private String government;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.homepage
     *
     * @mbg.generated
     */
    private String homepage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.householder
     *
     * @mbg.generated
     */
    private String householder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.marriage
     *
     * @mbg.generated
     */
    private String marriage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.msn
     *
     * @mbg.generated
     */
    private String msn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.nativity_address
     *
     * @mbg.generated
     */
    private String nativityAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.qq
     *
     * @mbg.generated
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.speciality
     *
     * @mbg.generated
     */
    private String speciality;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_info.version
     *
     * @mbg.generated
     */
    private Long version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.id
     *
     * @return the value of sys_user_info.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.id
     *
     * @param id the value for sys_user_info.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.user_id
     *
     * @return the value of sys_user_info.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.user_id
     *
     * @param userId the value for sys_user_info.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.head_portrait
     *
     * @return the value of sys_user_info.head_portrait
     *
     * @mbg.generated
     */
    public String getHeadPortrait() {
        return headPortrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.head_portrait
     *
     * @param headPortrait the value for sys_user_info.head_portrait
     *
     * @mbg.generated
     */
    public void setHeadPortrait(String headPortrait) {
        this.headPortrait = headPortrait == null ? null : headPortrait.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.address
     *
     * @return the value of sys_user_info.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.address
     *
     * @param address the value for sys_user_info.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.post_code
     *
     * @return the value of sys_user_info.post_code
     *
     * @mbg.generated
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.post_code
     *
     * @param postCode the value for sys_user_info.post_code
     *
     * @mbg.generated
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode == null ? null : postCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.height
     *
     * @return the value of sys_user_info.height
     *
     * @mbg.generated
     */
    public String getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.height
     *
     * @param height the value for sys_user_info.height
     *
     * @mbg.generated
     */
    public void setHeight(String height) {
        this.height = height == null ? null : height.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.weight
     *
     * @return the value of sys_user_info.weight
     *
     * @mbg.generated
     */
    public String getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.weight
     *
     * @param weight the value for sys_user_info.weight
     *
     * @mbg.generated
     */
    public void setWeight(String weight) {
        this.weight = weight == null ? null : weight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.birthday
     *
     * @return the value of sys_user_info.birthday
     *
     * @mbg.generated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.birthday
     *
     * @param birthday the value for sys_user_info.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.blood
     *
     * @return the value of sys_user_info.blood
     *
     * @mbg.generated
     */
    public String getBlood() {
        return blood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.blood
     *
     * @param blood the value for sys_user_info.blood
     *
     * @mbg.generated
     */
    public void setBlood(String blood) {
        this.blood = blood == null ? null : blood.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.culture
     *
     * @return the value of sys_user_info.culture
     *
     * @mbg.generated
     */
    public String getCulture() {
        return culture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.culture
     *
     * @param culture the value for sys_user_info.culture
     *
     * @mbg.generated
     */
    public void setCulture(String culture) {
        this.culture = culture == null ? null : culture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.finish_school_date
     *
     * @return the value of sys_user_info.finish_school_date
     *
     * @mbg.generated
     */
    public Date getFinishSchoolDate() {
        return finishSchoolDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.finish_school_date
     *
     * @param finishSchoolDate the value for sys_user_info.finish_school_date
     *
     * @mbg.generated
     */
    public void setFinishSchoolDate(Date finishSchoolDate) {
        this.finishSchoolDate = finishSchoolDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.folk
     *
     * @return the value of sys_user_info.folk
     *
     * @mbg.generated
     */
    public String getFolk() {
        return folk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.folk
     *
     * @param folk the value for sys_user_info.folk
     *
     * @mbg.generated
     */
    public void setFolk(String folk) {
        this.folk = folk == null ? null : folk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.government
     *
     * @return the value of sys_user_info.government
     *
     * @mbg.generated
     */
    public String getGovernment() {
        return government;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.government
     *
     * @param government the value for sys_user_info.government
     *
     * @mbg.generated
     */
    public void setGovernment(String government) {
        this.government = government == null ? null : government.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.homepage
     *
     * @return the value of sys_user_info.homepage
     *
     * @mbg.generated
     */
    public String getHomepage() {
        return homepage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.homepage
     *
     * @param homepage the value for sys_user_info.homepage
     *
     * @mbg.generated
     */
    public void setHomepage(String homepage) {
        this.homepage = homepage == null ? null : homepage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.householder
     *
     * @return the value of sys_user_info.householder
     *
     * @mbg.generated
     */
    public String getHouseholder() {
        return householder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.householder
     *
     * @param householder the value for sys_user_info.householder
     *
     * @mbg.generated
     */
    public void setHouseholder(String householder) {
        this.householder = householder == null ? null : householder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.marriage
     *
     * @return the value of sys_user_info.marriage
     *
     * @mbg.generated
     */
    public String getMarriage() {
        return marriage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.marriage
     *
     * @param marriage the value for sys_user_info.marriage
     *
     * @mbg.generated
     */
    public void setMarriage(String marriage) {
        this.marriage = marriage == null ? null : marriage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.msn
     *
     * @return the value of sys_user_info.msn
     *
     * @mbg.generated
     */
    public String getMsn() {
        return msn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.msn
     *
     * @param msn the value for sys_user_info.msn
     *
     * @mbg.generated
     */
    public void setMsn(String msn) {
        this.msn = msn == null ? null : msn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.nativity_address
     *
     * @return the value of sys_user_info.nativity_address
     *
     * @mbg.generated
     */
    public String getNativityAddress() {
        return nativityAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.nativity_address
     *
     * @param nativityAddress the value for sys_user_info.nativity_address
     *
     * @mbg.generated
     */
    public void setNativityAddress(String nativityAddress) {
        this.nativityAddress = nativityAddress == null ? null : nativityAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.qq
     *
     * @return the value of sys_user_info.qq
     *
     * @mbg.generated
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.qq
     *
     * @param qq the value for sys_user_info.qq
     *
     * @mbg.generated
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.speciality
     *
     * @return the value of sys_user_info.speciality
     *
     * @mbg.generated
     */
    public String getSpeciality() {
        return speciality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.speciality
     *
     * @param speciality the value for sys_user_info.speciality
     *
     * @mbg.generated
     */
    public void setSpeciality(String speciality) {
        this.speciality = speciality == null ? null : speciality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.description
     *
     * @return the value of sys_user_info.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.description
     *
     * @param description the value for sys_user_info.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_info.version
     *
     * @return the value of sys_user_info.version
     *
     * @mbg.generated
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_info.version
     *
     * @param version the value for sys_user_info.version
     *
     * @mbg.generated
     */
    public void setVersion(Long version) {
        this.version = version;
    }
}