package com.goku.coreui.sys.mapper;

import com.goku.coreui.sys.model.SysRoleAuth;

public interface SysRoleAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_auth
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_auth
     *
     * @mbg.generated
     */
    int insert(SysRoleAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_auth
     *
     * @mbg.generated
     */
    int insertSelective(SysRoleAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_auth
     *
     * @mbg.generated
     */
    SysRoleAuth selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_auth
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysRoleAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_auth
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysRoleAuth record);
}