package com.goku.coreui.sys.mapper;

import com.goku.coreui.sys.model.SysUserAuth;

public interface SysUserAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_auth
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_auth
     *
     * @mbg.generated
     */
    int insert(SysUserAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_auth
     *
     * @mbg.generated
     */
    int insertSelective(SysUserAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_auth
     *
     * @mbg.generated
     */
    SysUserAuth selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_auth
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysUserAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_auth
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysUserAuth record);
}